### ISSUE TITLE
sample specific offsets

### ISSUE THREAD

**Issue by gouthamatla** [natsuhiko/rasqual#26]
Hi Natsuhiko,

I would like to know why the sample specific offsets is mandatory. I have the normalized expression values that are also corrected for technical variation ( PEER residuals ) and VCF file with allelic counts. I am trying to run rasqual just by using the residuals ( -y ) but its showing an error `input files are not specified!`, preseumably its expecting -k i.e sample specific offsets. 

Doesnt it work with the residuals ? Does it expect to provide raw counts and it calculates sample specific offsets and needs a covariates file ( -x ) ?

Thanks,
Goutham A

**Comment by natsuhiko** [comment]
You cannot use the normalised expression value as the input (-y), because RASQUAL models the raw expression read count as a negative binomial distribution which requires an integer value input. This is because you need the offset to take account of the library size and potential GC bias in the model. 

Best regards,
Natsuhiko

**Comment by gouthamatla** [comment]
Thanks for the clarification.
